# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.auth.mail_from_email: 'bizbot64@gmail.com'
    app.auth.mail_from_name: 'BizHub'
    app.google_client_id: '%env(trim:GOOGLE_CLIENT_ID)%'
    app.google_client_secret: '%env(trim:GOOGLE_CLIENT_SECRET)%'
    app.auth0_domain: '%env(trim:AUTH0_DOMAIN)%'
    app.auth0_client_id: '%env(trim:AUTH0_CLIENT_ID)%'
    app.auth0_client_secret: '%env(trim:AUTH0_CLIENT_SECRET)%'
    face.api_key: '%env(FACE_API_KEY)%'
    face.api_secret: '%env(FACE_API_SECRET)%'
    app.cloudflare_api_token: '%env(default::CLOUDFLARE_API_TOKEN)%'
    app.cloudflare_acc_id: '%env(default::CLOUDFLARE_ACC_ID)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\Auth\AuthMailerService:
        arguments:
            $fromEmail: '%app.auth.mail_from_email%'
            $fromName: '%app.auth.mail_from_name%'

    App\Service\Auth\GoogleOAuthService:
        arguments:
            $googleClientId: '%app.google_client_id%'
            $googleClientSecret: '%app.google_client_secret%'

    App\Service\FacePlusPlus\FaceRecognitionService:
        arguments:
            $faceApiKey: '%face.api_key%'
            $faceApiSecret: '%face.api_secret%'

    App\Service\Ai\CloudflareAiService:
        arguments:
            $cloudflareApiToken: '%app.cloudflare_api_token%'
            $cloudflareAccountId: '%app.cloudflare_acc_id%'

    App\EventListener\MfaEnforcementListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
